//document.write('<center><h4>MyLinks</h4></center>');
document.write(' <a target="_blank" href="https://www.palpkschools.org/Page/20">Lindbergh</a>');
document.write(' <a target="_blank" href="https://www.palpkschools.org/Page/24">PPHS</a>');
document.write(' <a target="_blank" href="https://www.cooper.edu">Cooper Union</a>');
document.write(' <a target="_blank" href="https://www.syracuse.edu">SyracuseU</a>');
document.write(' <a target="_blank" href="https://www.cornell.edu">CornellU</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="https://www.nus.edu.sg">NUS</a>');
document.write(' <a target="_blank" href="https://www.princeton.edu/">PrincetonU</a>');
document.write(' <a target="_blank" href="https://www.a-star.edu.sg/i2r">I2R</a>');
document.write(' <a target="_blank" href="https://www.lmco.com">LMCO</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="https://www.ieee.org">IEEE</a>');
document.write(' <a target="_blank" href="https://www.aaia-ai.org/">AAIA</a>');
document.write(' <a target="_blank" href="https://www.itsoc.org">ITSOC</a>');
document.write(' <a target="_blank" href="https://www.comsoc.org">COMSOC</a>');
document.write(' <a target="_blank" href="https://www.sigmobile.org/">Sigmobile</a>');
document.write(' <a target="_blank" href="https://www.acm.org">ACM</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="https://www.state.nj.us/">NewJersey</a>');
document.write(' <a target="_blank" href="https://www.ridgefieldpark.org/">RidgefieldPark</a>');
document.write(' <a target="_blank" href="https://www.city-data.com/city/Palisades-Park-New-Jersey.html"> PalisadesPark</a>');
document.write(' <a target="_blank" href="https://www.princetonnj.gov/">Princeton</a>');
document.write(' <a target="_blank" href="https://www.ny.gov/">NewYork</a>');
document.write(' <a target="_blank" href="https://www.fingerlakes.org/">FingerLakes</a>');
document.write(' <a target="_blank" href="https://www.visitithaca.com/">Ithaca</a>');
document.write(' <a target="_blank" href="https://www.syracuse.com/">Syracuse</a>');
document.write(' <a target="_blank" href="https://www.sg/">Singapore</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=ireland">Ireland</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=venezia">Venezia</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=hawaii">Hawaii</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=Tallinn">Tallinn</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=prague">Prague</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=firenze">Firenze</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=kyoto">Kyoto</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=nara">Nara</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=paris">Paris</a>');
document.write(' <a target="_blank" href="https://en.wikipedia.org/wiki/French_Riviera">Nice</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=alaska">Alaska</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=australia">Australia</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=toronto">Toronto</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=grenoble">Grenoble</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=villard de lans">Villard-de-lans</a>');
document.write(' <a target="_blank" href="https://www.sg">Singapore</a>');
document.write(' <a target="_blank" href="https://en.wikipedia.org/wiki/Kuala_Lumpur">KL</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=penang">Penang</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=bangkok">Bangkok</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=bali">Bali</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=grandcanyon">Big Hole</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=las+vegas">Let It Roll</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=Oberstdorf">Oberstdorf</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=munich">Munich</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=cambodia">Cambodia</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=china">China</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=hong+kong">Hong Kong</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=montreal">Montreal</a>');
document.write(' <a target="_blank" href="https://www.google.com/search?q=vancouver">Vancouver</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="https://news.google.com/">GoogleNews</a>');
document.write(' <a target="_blank" href="https://www.foxnews.com/">FoxNews</a>');
document.write(' <a target="_blank" href="https://fivethirtyeight.com/">538</a>');
document.write(' <a target="_blank" href="https://www.realclearpolitics.com/">RCP</a>');
document.write(' <a target="_blank" href="https://www.huffingtonpost.com/">Huff</a>');
document.write(' <a target="_blank" href="https://crooksandliars.com/">Crooks-Liars</a>');
document.write(' <a target="_blank" href="https://www.mediaite.com/">Mediaite</a>');
//document.write(' <a target="_blank" href="https://news.yahoo.com/">YahooNews</a>');
//document.write(' <a target="_blank" href="https://digbysblog.blogspot.com/">Digby</a>');
document.write(' <a target="_blank" href="https://techcrunch.com/">Techcrunch</a>');
