//document.write('<center><h4>MyLinks</h4></center>');
document.write(' <a target="_blank" href="http://www.cooper.edu">Cooper Union</a>');
document.write(' <a target="_blank" href="http://www.syracuse.edu">Syracuse University</a>');
document.write(' <a target="_blank" href="http://www.cornell.edu">Cornell University</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="http://www.lmco.com">Lockheed Martin</a>');
document.write(' <a target="_blank" href="http://www.nus.edu.sg">National University of Singapore</a>');
document.write(' <a target="_blank" href="http://www.i2r.a-star.edu.sg">I2R</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="http://www.itsoc.org">Information Theory</a>');
document.write(' <a target="_blank" href="http://www.ieee.org">IEEE</a>');
document.write(' <a target="_blank" href="http://www.sigmobile.org/">Sigmobile</a>');
document.write(' <a target="_blank" href="http://www.acm.org">ACM</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="http://www.state.nj.us/">New Jersey</a>');
document.write(' <a target="_blank" href="http://www.ridgefieldpark.org/">Ridgefield Park</a>');
document.write(' <a target="_blank" href="http://www.city-data.com/city/Palisades-Park-New-Jersey.html"> Palisades Park</a>');
document.write(' <a target="_blank" href="http://www.ny.gov/">New York</a>');
document.write(' <a target="_blank" href="http://www.fingerlakes.org/">Finger Lakes</a>');
document.write(' <a target="_blank" href="http://www.visitithaca.com/">Ithaca</a>');
document.write(' <a target="_blank" href="http://www.syracuse.com/">Syracuse</a>');
document.write(' <a target="_blank" href="http://www.sg/">Singapore</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=ireland">Ireland</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=venezia">Venezia</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=hawaii">Hawaii</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=Tallinn">Tallinn</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=prague">Prague</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=firenze">Firenze</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=kyoto">Kyoto</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=nara">Nara</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=paris">Paris</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=cote d-azur">Cote d-azur</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=alaska">Alaska</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=australia">Australia</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=toronto">Toronto</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=grenoble">Grenoble</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=villard de lans">Villard-de-lans</a>');
document.write(' <a target="_blank" href="http://www.sg">Singapore</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=penang">Penang</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=bangkok">Bangkok</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=bali">Bali</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=grandcanyon">Big Hole</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=las vegas">Sin City</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=Oberstdorf">Oberstdorf</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=munich">Munich</a>');
document.write(' <a target="_blank" href="http://www.google.com/search?q=cambodia&btnI=i-m+feeling+lucky">Cambodge</a>');
document.write(' <hr>');
document.write(' <a target="_blank" href="http://news.google.com/">Google News</a>');
document.write(' <a target="_blank" href="http://news.yahoo.com/">Yahoo News</a>');
document.write(' <a target="_blank" href="https://fivethirtyeight.com/">538</a>');
document.write(' <a target="_blank" href="https://www.realclearpolitics.com/">RCP</a>');
document.write(' <a target="_blank" href="http://www.huffingtonpost.com/">Huff</a>');
document.write(' <a target="_blank" href="http://crooksandliars.com/">Crooks-Liars</a>');
document.write(' <a target="_blank" href="http://www.mediaite.com/">Mediaite</a>');
document.write(' <a target="_blank" href="http://digbysblog.blogspot.com/">Digby</a>');
document.write(' <a target="_blank" href="http://techcrunch.com/">Techcrunch</a>');
document.write(' <a target="_blank" href="http://www.foxnews.com/">Fox News</a>');
